
POST http://localhost:4000/api/restaurant/addNewRestaurant
Content-Type: application/json

{
    "name": "rest2",
    "name_en": "rest2_en",
    "name_ar": "rest2_ar",
    "name_he": "rest2_he",
    "location": "location2",
    "location_en": "location2_en",
    "location_ar": "location2_ar",
    "location_he": "location2_he",
    "active": true
}

###

// 61a53362b581473c7c5f5d71
// 61a5dbd968f3bff203f59f2b

POST http://localhost:4000/api/restaurant/addNewCategory
Content-Type: application/json

{
    "restaurantID": "61a53362b581473c7c5f5d71",
    "name": "Salads",
    "name_en": "Salads",
    "name_ar": "سلطات",
    "name_he": "סלטים"
}

###

POST http://localhost:4000/api/restaurant/addNewItem
Content-Type: application/json

{
    "restaurantID": "61a53362b581473c7c5f5d71",
    "name": "Water",
    "name_en": "Water",
    "name_ar": "ماء بارد",
    "name_he": "מים קרים",
    "price": 4,
    "quantity": 3,
    "url": "https://images.unsplash.com/photo-1614713899518-7ec14c1a3f00?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8d2F0ZXIlMjBjdXB8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60",
    "active": true
}

###

POST http://localhost:4000/api/restaurant/addNewAddition
Content-Type: application/json

{
    "restaurantID": "61a53362b581473c7c5f5d71",
    "name": "Doneness Level",
    "name_en": "Doneness Level",
    "name_ar": "درجة الاستواء",
    "name_he": "מידת עשייה",
    "singleChoice": true
}

###

POST http://localhost:4000/api/restaurant/addNewAdditionItem
Content-Type: application/json

{
    "restaurantID": "61a53362b581473c7c5f5d71",
    "name": "Rare",
    "name_en": "Rare",
    "name_ar": "ريير",
    "name_he": "ריאר",
    "isDefault": false,
    "price": 0,
    "quantity": 15
}


### 

///////////////////////////////////////////////////////////////////////////////////////////////////////

// 61a53362b581473c7c5f5d71
// 61a5dbd968f3bff203f59f2b

GET http://localhost:4000/api/restaurant/getSearch

###

GET http://localhost:4000/api/restaurant/getRestaurantData/61a53362b581473c7c5f5d71

### 

POST http://localhost:4000/api/restaurant/addCategoryToRestaurant/61a53362b581473c7c5f5d71
Content-Type: application/json

{
    "categoryID": "61b3ee9b233c71d282ad6780"
}

###

POST http://localhost:4000/api/restaurant/addItemToCategory/61b3ecbd233c71d282ad675e
Content-Type: application/json

{
    "itemId": "61b3f16a233c71d282ad67ad"
}

###

POST http://localhost:4000/api/restaurant/addAdditionToItem/61a5deb368f3bff203f59f3b
Content-Type: application/json

{
    "additionId": "61b4affa233c71d282ad6818"
}

###

getUserRestaurants