GET http://localhost:4000/api/calls/getCalls/61a53362b581473c7c5f5d71
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWI5OTZkZDE0MWYzMTkxOWI5NGExYiIsImlhdCI6MTYzNzU5Nzc0N30.-b5NTtXONSPvj6KovWsZdKKa7--J_4ZaGNwSxLQ5xPI

###

POST http://localhost:4000/api/calls/addNewCall
Content-Type: application/json

{
    "service": "Bill",
    "table": "table2",
    "name": "yousef",
    "restaurantID": "61a53362b581473c7c5f5d71"
}

###

PUT http://localhost:4000/api/calls/changeCallStatus
Content-Type: application/json

{
    "newStatus": "done",
    "callID": "61ac76e089a42e288d0393d3" ,
    "restaurantID": "61a53362b581473c7c5f5d71"
}